message updated chatbot
PhodzoW0l7/Portfolio pull request #2
Opened 2024-11-13 06:55 UTC by PhodzoW0l7

Integrating the chatbot to my previous personal portfolio

2024-11-13 07:25 UTC, Tepanyega requested changes
@PhodzoW0l7 
i think it will be better if you add "there" hahahahaha, like 
"hi, there"

2024-11-13 07:25 UTC, Tepanyega commented on index.html
> +      <p>Hi,<br>How can I help you today?</p>
@PhodzoW0l7 
i think it will be better if you add "there" hahahahaha, like 
"hi, there"

2024-11-13 07:43 UTC, alphineandre requested changes
Fix the files so we can review everything.

2024-11-13 07:43 UTC, alphineandre commented on index.html
The files look incomplete. the CSS and JS files are also not here so we are not able to review the chatbot fully

2024-11-13 09:02 UTC, bokangkhumalo approved these changes
Hi @PhodzoW0l7, Website is looking inviting and user friendly, i like the use of a bright color pallete and simle animations that give the user feedback.

2024-11-13 09:50 UTC, KhanyiCodes approved these changes, later dismissed

2024-11-13 09:51 UTC, KhanyiCodes commented on index.html
True, we can only see the HTML file.

2024-11-13 09:57 UTC, bokangkhumalo commented on index.html
@PhodzoW0l7, Agreed, im just here to support this review as i had noticed this at a later stage, please make sure this is updated for your next review before approval. Happy coding!

2024-11-13 09:58 UTC, bokangkhumalo requested changes
Hi, @PhodzoW0l7, please Ensure that all files are included in your files changed before you can merge.

2024-11-13 11:03 UTC, Tepanyega approved these changes

2024-11-15 09:00 UTC, PhodzoW0l7 commented on index.html
> +      <p>Hi,<br>How can I help you today?</p>
Noted.

2024-11-15 09:00 UTC, PhodzoW0l7 commented on style/chatstyle.css
Removed the styling file and added the styling to them main CSS which is style.css for better integration.

2024-11-15 09:00 UTC, PhodzoW0l7 commented on javascript/chatscript.js
@alphineandre @bokangkhumalo @KhanyiCodes  I added JavaScript information to feed my data with responses and works perfectly.

2024-11-15 09:00 UTC, PhodzoW0l7 commented on style/style.css
matching the colors for better visuals when user interacts with the chatbot.

2024-11-17 06:21 UTC, JKRakuba requested changes
Hey @PhodzoW0l7  I've noticed that the responsiveness of the website isn't showing the full navigation bar for small screens. Please also look into that

2024-11-19 06:12 UTC, alphineandre approved these changes
Everything looks good. Great work

2024-11-19 06:12 UTC, alphineandre commented on chatbot/main.js
Okay leaving no stone unturned i see.

2024-11-19 06:12 UTC, alphineandre commented on chatbot/index.html
Looks good

2024-11-19 13:23 UTC, bokangkhumalo approved these changes
Awesome work @PhodzoW0l7, nice to see some advanced features implemented!

2024-11-19 21:08 UTC, JKRakuba approved these changes
Well done!

2024-11-20 06:09 UTC, KhanyiCodes approved these changes

2024-11-20 06:13 UTC, merged